export const ADD_RECIPE = "ADD_RECIPE"
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const ADD_STEP = "ADD_STEP"
export const ADD_BASIC_INFO = "ADD_BASIC_INFO"
export const EDIT_RECIPE = "EDIT_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const  = ""
export const  = ""
